### ISSUE TITLE
Launch Checklist 

### ISSUE THREAD

**Issue by jessiofhall** [djangocon/2017.djangocon.us#9]
- [x] Don't forget a favicon 
- [ ] Jekyll integration complete
- [ ] Content Populated (DEFNA Team)
- [ ] QA Complete 
- [ ] Bugs Resolved 
- [ ] DNS Switched
